# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kresimir/Downloads/OpenKKND

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kresimir/Downloads/OpenKKND/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kresimir/Downloads/OpenKKND/build/CMakeFiles /home/kresimir/Downloads/OpenKKND/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kresimir/Downloads/OpenKKND/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenKKND

# Build rule for target.
OpenKKND: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenKKND
.PHONY : OpenKKND

# fast build rule for target.
OpenKKND/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OpenKKND.dir/build.make CMakeFiles/OpenKKND.dir/build
.PHONY : OpenKKND/fast

#=============================================================================
# Target rules for targets named Unsorted

# Build rule for target.
Unsorted: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Unsorted
.PHONY : Unsorted

# fast build rule for target.
Unsorted/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Unsorted.dir/build.make src/CMakeFiles/Unsorted.dir/build
.PHONY : Unsorted/fast

#=============================================================================
# Target rules for targets named Audio

# Build rule for target.
Audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Audio
.PHONY : Audio

# fast build rule for target.
Audio/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Audio.dir/build.make src/CMakeFiles/Audio.dir/build
.PHONY : Audio/fast

#=============================================================================
# Target rules for targets named Video

# Build rule for target.
Video: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Video
.PHONY : Video

# fast build rule for target.
Video/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Video.dir/build.make src/CMakeFiles/Video.dir/build
.PHONY : Video/fast

#=============================================================================
# Target rules for targets named Application

# Build rule for target.
Application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Application
.PHONY : Application

# fast build rule for target.
Application/fast:
	$(MAKE) $(MAKESILENT) -f src/Application/CMakeFiles/Application.dir/build.make src/Application/CMakeFiles/Application.dir/build
.PHONY : Application/fast

#=============================================================================
# Target rules for targets named ApplicationScripts

# Build rule for target.
ApplicationScripts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ApplicationScripts
.PHONY : ApplicationScripts

# fast build rule for target.
ApplicationScripts/fast:
	$(MAKE) $(MAKESILENT) -f src/Application/Scripts/CMakeFiles/ApplicationScripts.dir/build.make src/Application/Scripts/CMakeFiles/ApplicationScripts.dir/build
.PHONY : ApplicationScripts/fast

#=============================================================================
# Target rules for targets named Engine

# Build rule for target.
Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Engine
.PHONY : Engine

# fast build rule for target.
Engine/fast:
	$(MAKE) $(MAKESILENT) -f src/Engine/CMakeFiles/Engine.dir/build.make src/Engine/CMakeFiles/Engine.dir/build
.PHONY : Engine/fast

#=============================================================================
# Target rules for targets named Infrastructure

# Build rule for target.
Infrastructure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Infrastructure
.PHONY : Infrastructure

# fast build rule for target.
Infrastructure/fast:
	$(MAKE) $(MAKESILENT) -f src/Infrastructure/CMakeFiles/Infrastructure.dir/build.make src/Infrastructure/CMakeFiles/Infrastructure.dir/build
.PHONY : Infrastructure/fast

#=============================================================================
# Target rules for targets named InfrastructurePlatformSpecific

# Build rule for target.
InfrastructurePlatformSpecific: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InfrastructurePlatformSpecific
.PHONY : InfrastructurePlatformSpecific

# fast build rule for target.
InfrastructurePlatformSpecific/fast:
	$(MAKE) $(MAKESILENT) -f src/Infrastructure/PlatformSpecific/CMakeFiles/InfrastructurePlatformSpecific.dir/build.make src/Infrastructure/PlatformSpecific/CMakeFiles/InfrastructurePlatformSpecific.dir/build
.PHONY : InfrastructurePlatformSpecific/fast

#=============================================================================
# Target rules for targets named InfrastructureRenderer

# Build rule for target.
InfrastructureRenderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InfrastructureRenderer
.PHONY : InfrastructureRenderer

# fast build rule for target.
InfrastructureRenderer/fast:
	$(MAKE) $(MAKESILENT) -f src/Infrastructure/Renderer/CMakeFiles/InfrastructureRenderer.dir/build.make src/Infrastructure/Renderer/CMakeFiles/InfrastructureRenderer.dir/build
.PHONY : InfrastructureRenderer/fast

#=============================================================================
# Target rules for targets named InfrastructureWindow

# Build rule for target.
InfrastructureWindow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InfrastructureWindow
.PHONY : InfrastructureWindow

# fast build rule for target.
InfrastructureWindow/fast:
	$(MAKE) $(MAKESILENT) -f src/Infrastructure/Window/CMakeFiles/InfrastructureWindow.dir/build.make src/Infrastructure/Window/CMakeFiles/InfrastructureWindow.dir/build
.PHONY : InfrastructureWindow/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Application"
	@echo "... ApplicationScripts"
	@echo "... Audio"
	@echo "... Engine"
	@echo "... Infrastructure"
	@echo "... InfrastructurePlatformSpecific"
	@echo "... InfrastructureRenderer"
	@echo "... InfrastructureWindow"
	@echo "... OpenKKND"
	@echo "... Unsorted"
	@echo "... Video"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

